[package]
name = "variables"
version = "0.1.0"
authors = ["ruairidhm98 <2250079m@student.gla.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
